language: generic
sudo: required
dist: trusty
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  global:
  - EMACS_DIR=$HOME/emacs
  - EMACSBIN=$HOME/emacs/src/emacs
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=26.2
  - EMACS_VERSION=snapshot
before_install:
- sudo apt install gnutls-bin
- curl -OL https://raw.githubusercontent.com/vermiculus/emake.el/master/build-emacs
# You generally don't want 'x' in your own projects, but for the
# purposes of actually developing `build-emacs', it's useful
# information to have.  See the example for how you *should* be
# doing all this!
- bash -ex build-emacs
install:
- $EMACSBIN --version
- make makel.mk
- make makel-version
- make install-elpa-dependencies
- make -f org-starter-swiper.mk install-elpa-dependencies
script:
- make check
- make -f org-starter-swiper.mk check
